
platform :ios, '8.0'

use_frameworks!

target 'AWSWrapper_Example' do
  pod 'AWSWrapper', :path => '../'

  target 'AWSWrapper_Tests' do
    inherit! :search_paths
    pod 'AWSWrapper', :path => '../'
    
    pod 'Specta'
  pod 'Expecta'
  end
  
  target 'AWSWrapper_LoginTests' do
    inherit! :search_paths
    pod 'AWSWrapper', :path => '../'
    
    pod 'Specta'
    pod 'Expecta'
  end
end
