//
//  AWSConfiguration.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.16
//
//

#import <Foundation/Foundation.h>
#import <AWSCore/AWSCore.h>

// Configuration for Cognito User Pools
FOUNDATION_EXPORT NSString *const AWSCognitoUserPoolId;
FOUNDATION_EXPORT NSString *const AWSCognitoUserPoolClientId;
FOUNDATION_EXPORT NSString *const AWSCognitoUserPoolClientSecret;
FOUNDATION_EXPORT AWSRegionType const AWSCognitoUserPoolRegion;
