//
//  AWSConfiguration.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.16
//
//

#import "AWSConfiguration.h"



// Cognito User Pools Identity Id
NSString *const AWSCognitoUserPoolId = @"us-east-1_2WqVQYNVu";

// Cognito User Pools App Client Id
NSString *const AWSCognitoUserPoolClientId = @"ibag2n69s0iikmbjvgr61cpg0";

// Cognito User Pools Client Secret
NSString *const AWSCognitoUserPoolClientSecret = @"1h8pn5qc6f5ac7q80fnr1gaglke0mm2tc5upqo14a2h27p0fskbj";

// Cognito User Pools Region
AWSRegionType const AWSCognitoUserPoolRegion = AWSRegionUSEast1;
