//
//  NoSQLModelHelpers.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.16
//
#import "NoSQLModelHelpers.h"

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wprotocol"

NSString *const GetItem = @"GetItem";
NSString *const QueryWithPartitionKey = @"QueryWithPartitionKey";
NSString *const QueryWithPartitionKeyAndFilter = @"QueryWithPartitionKeyAndFilter";
NSString *const QueryWithPartitionKeyAndSortKey = @"QueryWithPartitionKeyAndSortKey";
NSString *const QueryWithPartitionKeyAndSortKeyAndFilter = @"QueryWithPartitionKeyAndSortKeyAndFilter";
NSString *const Scan = @"Scan";
NSString *const ScanWithFilter = @"ScanWithFilter";

@implementation Index

@end

@interface Table()

@property (nonatomic, strong) NSArray<NSString *> *orderedAttributeKeys;
@property (nonatomic, strong) AWSDynamoDBObjectModel<AWSDynamoDBModeling> *model;
@property (nonatomic, strong) NSArray<Index *> *indexes;

@end

@implementation Table

- (void)setModel:(AWSDynamoDBObjectModel<AWSDynamoDBModeling> *)model {
    _tableName = [[model class] dynamoDBTableName];
    _partitionKeyName = [[model class] hashKeyAttribute];
    if ([[model class] respondsToSelector:@selector(rangeKeyAttribute)]) {
        _sortKeyName = [[model class] rangeKeyAttribute];
    }
    [self produceOrderedAttributeKeys:model];
}

- (void)produceOrderedAttributeKeys:(AWSDynamoDBObjectModel<AWSDynamoDBModeling> *)model {
    NSMutableArray *keys = [[[model dictionaryValue] allKeys] mutableCopy];
    [keys sortUsingComparator:^NSComparisonResult(NSString * _Nonnull obj1, NSString * _Nonnull obj2) {
        return [obj1 compare:obj2];
    }];

    if ([[model class] respondsToSelector:@selector(rangeKeyAttribute)]) {
        NSString *rangeKeyAttribute = [[model class] rangeKeyAttribute];
        [keys removeObject:rangeKeyAttribute];
        [keys insertObject:rangeKeyAttribute atIndex:0];
    }

    NSString *hashKeyAttribute = [[model class] hashKeyAttribute];
    [keys removeObject:hashKeyAttribute];
    [keys insertObject:hashKeyAttribute atIndex:0];

    self.orderedAttributeKeys = [NSArray arrayWithArray:keys];
}

/**
 * Converts attribute name from data object format to table format. This should
 * be overridden by each table class.
 * @param dataObjectAttributeName data object attribute name
 * @return table attribute name
 */
- (NSString*)tableAttributeName:(NSString*)dataObjectAttributeName {
    return dataObjectAttributeName;
}

@end

#pragma clang diagnostic pop
