//
//  NoSQLModelHelpers.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.16
//
#import <Foundation/Foundation.h>
#import "AWSDynamoDB/AWSDynamoDB.h"

NS_ASSUME_NONNULL_BEGIN

FOUNDATION_EXPORT NSString *const GetItem;
FOUNDATION_EXPORT NSString *const QueryWithPartitionKey;
FOUNDATION_EXPORT NSString *const QueryWithPartitionKeyAndFilter;
FOUNDATION_EXPORT NSString *const QueryWithPartitionKeyAndSortKey;
FOUNDATION_EXPORT NSString *const QueryWithPartitionKeyAndSortKeyAndFilter;
FOUNDATION_EXPORT NSString *const Scan;
FOUNDATION_EXPORT NSString *const ScanWithFilter;

@protocol IndexOperations <NSObject>

- (NSArray<NSString *> *)supportedOperations;

@optional

- (NSString *)queryWithPartitionKeyDescription;

- (void)queryWithPartitionKeyWithCompletionHandler:(void (^)(AWSDynamoDBPaginatedOutput * _Nullable response, NSError * _Nullable error))completionHandler;

- (NSString *)queryWithPartitionKeyAndFilterDescription;

- (void)queryWithPartitionKeyAndFilterWithCompletionHandler:(void (^)(AWSDynamoDBPaginatedOutput * _Nullable response, NSError * _Nullable error))completionHandler;

- (NSString *)queryWithPartitionKeyAndSortKeyDescription;

- (void)queryWithPartitionKeyAndSortKeyWithCompletionHandler:(void (^)(AWSDynamoDBPaginatedOutput * _Nullable response, NSError * _Nullable error))completionHandler;

- (NSString *)queryWithPartitionKeyAndSortKeyAndFilterDescription;

- (void)queryWithPartitionKeyAndSortKeyAndFilterWithCompletionHandler:(void (^)(AWSDynamoDBPaginatedOutput * _Nullable response, NSError * _Nullable error))completionHandler;

@end

@protocol TableOperations <NSObject>

- (NSString *)getItemDescription;

- (void)getItemWithCompletionHandler:(void (^)(AWSDynamoDBObjectModel<AWSDynamoDBModeling> * _Nullable response, NSError * _Nullable error))completionHandler;

- (NSString *)scanDescription;

- (void)scanWithCompletionHandler:(void (^)(AWSDynamoDBPaginatedOutput * _Nullable response, NSError * _Nullable error))completionHandler;

- (NSString *)scanWithFilterDescription;

- (void)scanWithFilterWithCompletionHandler:(void (^)(AWSDynamoDBPaginatedOutput * _Nullable response, NSError * _Nullable error))completionHandler;

- (void)insertSampleDataWithCompletionHandler:(void (^)(NSArray<NSError *> * _Nullable errors))completionHandler;

- (void)removeSampleDataWithCompletionHandler:(void (^)(NSArray<NSError *> * _Nullable errors))completionHandler;

- (void)updateItem:(AWSDynamoDBObjectModel<AWSDynamoDBModeling> *)item
 completionHandler:(void (^)(NSError * _Nullable error))completionHandler;

- (void)removeItem:(AWSDynamoDBObjectModel<AWSDynamoDBModeling> *)item
 completionHandler:(void (^)(NSError * _Nullable error))completionHandler;

@end

@interface Index : NSObject <IndexOperations>

@property (nonatomic, strong, readonly, nullable) NSString *indexName;

@end

@interface Table : NSObject <TableOperations>

/**
 * Converts attribute name from data object format to table format. This should
 * be overridden by each derived table class.
 * @param dataObjectAttributeName data object attribute name
 * @return table attribute name
 */
- (NSString*)tableAttributeName:(NSString*)dataObjectAttributeName;

@property (nonatomic, readonly) NSString *tableName;
@property (nonatomic, readonly) NSString *tableDisplayName;
@property (nonatomic, readonly) NSString *partitionKeyName;
@property (nonatomic, strong) NSString *partitionKeyType;
@property (nonatomic, readonly, nullable) NSString *sortKeyName;
@property (nonatomic, nullable) NSString *sortKeyType;
@property (nonatomic, readonly) AWSDynamoDBObjectModel<AWSDynamoDBModeling> *model;
@property (nonatomic, readonly) NSArray<Index *> *indexes;
@property (nonatomic, readonly) NSArray<NSString *> *orderedAttributeKeys;

@end

NS_ASSUME_NONNULL_END
