//
//  NoSQLSampleDataGenerator.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.16
//
#import <Foundation/Foundation.h>

@interface NoSQLSampleDataGenerator : NSObject

+ (NSNumber *)randomPartitionSampleNumber;

+ (NSString *)randomPartitionSampleStringWithAttributeName:(NSString *)attributeName;

+ (NSData *)randomPartitionSampleBinary;

+ (NSNumber *)randomSampleNumber;

+ (NSString *)randomSampleStringWithAttributeName:(NSString *)attributeName;

+ (NSNumber *)randomSampleBOOL;

+ (NSData *)randomSampleBinary;

+ (NSSet<NSString *> *)randomSampleStringSet;

+ (NSSet<NSNumber *> *)randomSampleNumberSet;

+ (NSSet<NSData *> *)randomSampleBinarySet;

+ (NSArray<NSString *> *)randomSampleStringArray;

+ (NSDictionary<NSString *, NSString *> *)randomSampleMap;

@end
