//
//  RecentVisit.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.16
//

@import UIKit;
#import <AWSDynamoDB/AWSDynamoDB.h>
#import "NoSQLModelHelpers.h"
#import "RecordSuitable.h"

NS_ASSUME_NONNULL_BEGIN


@interface RecentVisit : AWSDynamoDBObjectModel <AWSDynamoDBModeling, RecordSuitable>

+ (NSDictionary *)JSONKeyPathsByPropertyKey;

@property (nonatomic, strong) NSString *_userId;
@property (nonatomic, strong) NSString *_id;
@property (nonatomic, strong) NSString *_commitId;
@property (nonatomic, strong) NSString *_remoteHash;
@property (nonatomic, strong) NSDictionary *_dicts;

@end

NS_ASSUME_NONNULL_END
