//
//  UserPoolMFAViewController.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.16
//
//

#import "UserPoolMFAViewController.h"

@interface UserPoolMFAViewController () 

@property (weak, nonatomic) IBOutlet UILabel *cancel;

@end

@implementation UserPoolMFAViewController

#pragma mark - UIViewController

- (void) viewWillAppear:(BOOL)animated {
    self.codeSentTo.text = self.destination;
    self.authenticationCode.text = nil;
}

- (void)viewDidLoad {
    [super viewDidLoad];

}

- (IBAction)onSignIn:(id)sender {
    self.mfaCodeCompletionSource.result = self.authenticationCode.text;
}

- (IBAction)onCancel:(id)sender {
    [self.navigationController popViewControllerAnimated:YES];
}

@end
